### ISSUE TITLE
Cannot open libhostfxr.so

### ISSUE THREAD

**Issue by nkosi23** [Servarr/dotnet-bsd#7]
When using the latest release, I get the following error message:

> Failed to load ~/dotnet-sdk-5.0.401-freebsd-x64/host/fxr/5.0.10/libhostfxr.so, error: Cannot open "~/dotnet-sdk-5.0.401-freebsd-x64/host/fxr/5.0.10/libhostfxr.so"
> The library libhostfxr.so was found, but loading it from ~/dotnet-sdk-5.0.401-freebsd-x64/host/fxr/5.0.10/libhostfxr.so failed
>   - Installing .NET prerequisites might help resolve this problem.
>      https://go.microsoft.com/fwlink/?linkid=2063370

All i did was to naively unzip the prebuilt sdk, and run "./dotnet -h". I didn't patched, unzipped or copied around anything else. 

I am looking for a prebuilt SDK working out-of-box on FreeBSD 12 to do some urgent development work for a client :worried:

**Comment by ta264** [comment]
Did you install the dependencies?

**Comment by nkosi23** [comment]
@ta264 Thank you for your help! No I haven't, what are the dependencies? Is there some documentation somewhere?

**Comment by sec** [comment]
Did you do `tar xfv dotnet-sdk-5.0.401-freebsd-x64.tar.gz` - I tried newest 5 release and it's working fine (you only need to do one quick fix `sed -i.ORI 's/osx-x64/osx-x64;freebsd-x64/' sdk/5.0.401//Microsoft.NETCoreSdk.BundledVersions.props` - if you're not familiar with FreeBSD, maybe you should develop on Linux/Windows or other OS supported by .NET - FreeBSD is not supported by MS, only by folks from community :)

**Comment by nkosi23** [comment]
Thanks a lot for your assistance, you pointed me in the right now everything works. I actually needed to set read permissions on all files for my user (all permissions were empty after unzipping). dotnet -h worked fine after that, but I neverless applied your fix. 

I've been using FreeBSD on servers for 2-3 years, and as my main workstation for about 2 years, no guru here but I have fairly good understanding of Unix and FreeBSD fundamentals at this point :smile: 

Once this is said, I have been contemplating using OpenSuse for my workstation, because of this kind of things and other ones (hardware support etc...). but unfortunately this is not an option for the next few months at least (no bandwidth whatsoever for such a migration among other things).
