### ISSUE TITLE
FreeBSD 13 issues

### ISSUE THREAD

**Issue by rmszc81** [Servarr/dotnet-bsd#9]
Hello my friend,
first, thanks for the great work to make this possible.

As a veteran .NET developer and a veteran/newbie in FreeBSD (well, almost 10 years without touch FreeBSD), I decided to give a try to these packages.

Extraction was quite fine, I look in Ubuntu to see where I should extract and I saw that /usr/share/dotnet was the best fit.

Then, I saw in linux that there's a symbolic link at /usr/bin/dotnet that points to /usr/share/dotnet/dotnet and I replicated this too.

I even compared the file list between .net 6 in ubuntu with the freebsd version of this package and all the files are present (except those ones that belongs to linux natively).

my first try? run ```dotnet``` without any parameters and bingo, it works.

then, I decided to be more aggressive and run ```dotnet --info``` and boom! Failed to load a library!

details below:

```
root@freebsd13:~ # dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
```

```
root@freebsd13:~ # dotnet --info
Failed to load /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.1/libcoreclr.so, error: Shared object "libunwind-x86_64.so.8" not found, required by "libcoreclr.so"
Segmentation fault (core dumped)
```

then I checked for corresponding packages:

```
root@freebsd13:~ # pkg search libunwind
libunwind-20201110             Generic stack unwinding library
linux-c7-libunwind-1.2         Generic stack unwinding library (Linux CentOS 7.9.2009)
```

here's my system info:

```
root@freebsd13:~ # uname -a
FreeBSD freebsd13.local 13.0-RELEASE-p4 FreeBSD 13.0-RELEASE-p4 #0: Tue Aug 24 07:33:27 UTC 2021     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
```

am I missing something?
Thank you very much!

**Comment by ta264** [comment]
You were missing dependencies as mentioned in the runtime issue
